name: publish

on: [push]

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest # for Arm based macs (M1 and above).
            args: --target aarch64-apple-darwin
          - platform: macos-latest # for Intel based macs.
            args: --target x86_64-apple-darwin
          - platform: ubuntu-22.04
            args: ''
          - platform: ubuntu-22.04-arm
            args: ''
          - platform: windows-latest
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: .

      - name: Install dependencies (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        # No version specification required as pnpm's version has been
        # pinned in package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm # Set this to npm, yarn or pnpm.

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: pnpm install # change this to npm or pnpm depending on which one you use.

      - name: Build Tauri app
        run: pnpm build ${{ matrix.args }}

      - name: Debug
        run: pnpm --package=tree-cli dlx tree -l 4 --ignore node_modules

      - name: Upload Artifact (macOS)
        uses: actions/upload-artifact@v4
        if: runner.os == 'macOS'
        with:
          name: App-${{ runner.os }}-${{ runner.arch }}-DMG
          path: ./src-tauri/*/release/bundle/dmg/*.dmg
      
      - name: Upload Artifact (Linux, DEB)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ runner.os }}-${{ runner.arch }}-DEB
          path: ./src-tauri/target/release/bundle/**/*.deb
      
      - name: Upload Artifact (Linux, AppImage)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ runner.os }}-${{ runner.arch }}-AppImage
          path: ./src-tauri/target/release/bundle/**/*.AppImage(.sig)
      
      - name: Upload Artifact (Linux, RPM)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ runner.os }}-${{ runner.arch }}}-RPM
          path: ./src-tauri/target/release/bundle/**/*.rpm
      
      - name: Upload Artifact (Windows, MSI)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ runner.os }}-${{ runner.arch }}-MSI
          path: ./src-tauri/target/release/bundle/**/*.msi
      
      - name: Upload Artifact (Windows, NSIS)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ runner.os }}-${{ runner.arch }}-NSIS
          path: ./src-tauri/target/release/bundle/**/*.exe

      - name: Upload Artifact (Windows, EXE)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ runner.os }}-${{ runner.arch }}-EXE
          path: ./src-tauri/target/release/*.exe
